buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project. buildDir = "${rootProject.buildDir}/${project.name}"
    
    // ✅ Force BuildConfig after project evaluation
    plugins.withId("com.android.library") {
        android {
            buildFeatures {
                buildConfig = true
            }
        }
    }
    
    plugins.withId("com.android.application") {
        android {
            buildFeatures {
                buildConfig = true
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}